sudo: false
language: node_js
node_js:
- '8'
- '6'
cache:
  directories:
  - node_modules
install: npm i
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: "jaime.ram@gmail.com"
  api_key:
    secure: XXhk61hyS3tYYQuqIlsnf8qv4GzpwRBAlORRURPJnGaNwL8vf1TImIs4At2GBp3riAgMMsXIdE8ZwU5SYhpTcE+UgeQQ4adBJRBruJ9rVNzhUkNsuQlfbqI4M3GZskQ6Ju2iz0gjrPKWJ0mUkDC1oQsDDnghTM6+8LKUXQ588iJ9TkQm6rvBQg6I45LloqJQb61eMUmGScYSOgqFTG8lH+HrWKNn7q3m7Nl+1Dufp9azoyxORfUt564sEDOCYpLxbSVsP6k69dw+e8EO1uYz0ZxW4gRuxnuuoaVf3gd6KI0kyBzAIR/GZbh/4RUx/Ie9ezPROcC5TJQfjgHbCEglMRS70Gx3s5LT616uTCPw/lnQ4/XjLFi16HopBv4vOsSQDb+wf/vhwz4QVp5rR4Tz+nJ4YnYx7N9DaO+2T+sY7SUywgUacthlJZ1bTKku4P4uuuOFVcYUn0QGkk8ckkDwX5hw4FhfT3s+TwcXnhPVBVLC8E+uH2J14xnuD5WSPIgF+Q0ZYAn6ChOSj+1Pziz/WnK1YY7HxKWYb3EaJ2xC5f2gMT7brRekhYSMi+4o/J7jwcDIW8m9MneKg8vsofs/U2WLTRQqNnNH6WvFeaH1/aJh90K5wGWEGvCO4qXrDx1QTNY0KriN4VM7HIE7I+whLumYCufboJvKspK08YxYQB0=
  on:
    tags: true
    node: '8'